#!/bin/bash

for IF in $(. lib/iw ESSID:off/any);  do
    . macreset ${IF}
    sudo airmon-ng start ${IF}
done

for IF in $(. lib/iw encap:UNSPEC);  do
    . macreset  ${IF}
done

iwconfig 2>/dev/null
