#!/bin/bash

#" " "-" "_" "." "/" ":" "\\" "," "|" "!" "@" "#" "$" "%" "^" "&" "*" "+" "~" "="

for del in " "; do
    for year in {1960..2016}; do
        for month in {01..12}; do
	    for day in {01..31}; do
    	        echo "$year$del$month$del$day"
#                echo "$day$del$month$del$year"
    	    done
	done
    done
done




